/**
 * 批次補上中文翻譯（硬編碼對照表 + 去除英文前綴）
 */
import { writeFileSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const dataPath = join(ROOT, 'data.json');

const ZH_MAP = {
  acknowledge: '承認；認可',
  adapt: '適應；改編',
  adequate: '足夠的；適當的',
  admire: '欽佩；讚賞',
  advantage: '優勢；好處',
  aesthetic: '美學的；審美的',
  affect: '影響；感動',
  aggressive: '侵略性的；積極進取的',
  allocate: '分配；撥出',
  ambitious: '有野心的；雄心勃勃的',
  analyze: '分析；解析',
  apparent: '明顯的；表面上的',
  appreciate: '欣賞；感激；增值',
  approve: '批准；贊同',
  articulate: '清楚表達；發音清晰的',
  assess: '評估；評定',
  assume: '假設；承擔',
  attach: '附加；貼上；依附',
  attain: '達到；獲得',
  attribute: '歸因於；屬性',
  authentic: '真實的；正宗的',
  available: '可用的；有空的',
  awkward: '尷尬的；笨拙的',
  betray: '背叛；洩露',
  bias: '偏見；偏差',
  boundary: '邊界；界限',
  burden: '負擔；重擔',
  capture: '捕捉；佔領；吸引',
  category: '類別；範疇',
  challenge: '挑戰；質疑',
  chaos: '混亂；混沌',
  clarify: '澄清；闡明',
  collaborate: '合作；協作',
  commit: '承諾；犯（罪）；投入',
  communicate: '溝通；傳達',
  compensate: '補償；賠償',
  compete: '競爭；比賽',
  complement: '補充；互補',
  comply: '遵守；順從',
  comprehend: '理解；領悟',
  compromise: '妥協；折衷',
  concentrate: '集中；專注；濃縮',
  conclude: '結論；結束',
  conduct: '進行；引導；行為',
  confident: '自信的；有把握的',
  conflict: '衝突；矛盾',
  confront: '面對；對抗',
  consensus: '共識；一致意見',
  consequence: '後果；結果',
  consider: '考慮；認為',
  consist: '由…組成；在於',
  constitute: '構成；組成；設立',
  construct: '建造；構建',
  consume: '消耗；消費；吃喝',
  contemplate: '沉思；考慮；凝視',
  contrast: '對比；對照',
  contribute: '貢獻；捐獻；促成',
  convince: '說服；使確信',
  cooperate: '合作；配合',
  crucial: '至關重要的；關鍵的',
  cultivate: '培養；耕種',
  debate: '辯論；討論',
  deceive: '欺騙；蒙蔽',
  dedicate: '奉獻；致力於',
  defeat: '擊敗；挫敗',
  deliberate: '故意的；深思熟慮的',
  demonstrate: '展示；證明；示範',
  depict: '描繪；描述',
  deplete: '耗盡；消耗',
  designate: '指定；命名',
  despite: '儘管；不管',
  determine: '決定；確定',
  devote: '奉獻；致力於',
  discipline: '紀律；學科；訓練',
  disclose: '揭露；公開',
  discrete: '離散的；分開的',
  discriminate: '歧視；區分',
  dispose: '處理；丟棄；安排',
  dispute: '爭議；爭論',
  distribute: '分配；分發；散布',
  diverse: '多樣的；不同的',
  dominate: '主導；支配',
  draft: '草稿；草案；徵兵',
  drastic: '激烈的；極端的',
  durable: '耐用的；持久的',
  eliminate: '消除；淘汰',
  embrace: '擁抱；接受；包含',
  emotion: '情感；情緒',
  emphasize: '強調；著重',
  encounter: '遭遇；偶遇',
  encourage: '鼓勵；促進',
  endure: '忍受；持續',
  enforce: '執行；強制',
  enhance: '增強；提升',
  enormous: '巨大的；龐大的',
  enterprise: '企業；事業；進取心',
  enthusiasm: '熱情；熱忱',
  environment: '環境；自然環境',
  equivalent: '相等的；等同物',
  essential: '必要的；本質的',
  establish: '建立；設立；確立',
  evident: '明顯的；明確的',
  evolve: '演化；逐步發展',
  examine: '檢查；考試；審查',
  exceed: '超過；超越',
  exclude: '排除；排斥',
  execute: '執行；實施；處決',
  exhibit: '展覽；展示；表現',
  expand: '擴展；擴大',
  expose: '暴露；揭發；使接觸',
  extensive: '廣泛的；大量的',
  extract: '提取；摘錄',
  facilitate: '促進；使便利',
  faithful: '忠誠的；忠實的',
  fascinate: '使著迷；使入迷',
  feature: '特色；特徵；功能',
  flexible: '靈活的；有彈性的',
  forecast: '預測；預報',
  formal: '正式的；正規的',
  foundation: '基礎；基金會；地基',
  fragment: '碎片；片段',
  frequent: '頻繁的；經常的',
  fulfill: '實現；履行；滿足',
  generate: '產生；生成',
  genuine: '真正的；真誠的',
  gradual: '漸進的；逐步的',
  guarantee: '保證；擔保',
  heritage: '遺產；傳統',
  hesitate: '猶豫；遲疑',
  highlight: '強調；突出；亮點',
  hypothesis: '假說；假設',
  identify: '識別；確認；認同',
  ignore: '忽視；忽略',
  immense: '巨大的；無限的',
  impact: '影響；衝擊',
  implicate: '牽連；暗示',
  implicit: '含蓄的；隱含的',
  impulse: '衝動；脈衝',
  incentive: '激勵；誘因；獎勵',
  incline: '傾向；傾斜',
  incorporate: '納入；合併；成立公司',
  individual: '個人的；個別的；個體',
  inevitable: '不可避免的；必然的',
  influence: '影響；感化；影響力',
  inform: '通知；告知',
  inhibit: '抑制；阻礙',
  initial: '最初的；開頭的',
  innovate: '創新；革新',
  insight: '洞察力；見解',
  inspire: '啟發；激勵；鼓舞',
  institute: '機構；學院；設立',
  integrity: '正直；完整性',
  intellect: '智力；才智',
  interact: '互動；交流',
  interpret: '解釋；口譯',
  intimate: '親密的；私密的',
  intrinsic: '內在的；固有的',
  invest: '投資；投入',
  investigate: '調查；研究',
  isolate: '隔離；孤立',
  justify: '證明…正當；為…辯護',
  kinetic: '動力的；運動的',
  landscape: '風景；景觀；格局',
  legitimate: '合法的；正當的',
  leverage: '槓桿；利用；影響力',
  likewise: '同樣地；也',
  maintain: '維持；保養；主張',
  manipulate: '操縱；操控',
  marginal: '邊際的；微小的',
  mechanism: '機制；機械裝置',
  mediate: '調解；斡旋',
  migrate: '遷移；移民',
  minimize: '最小化；減到最少',
  monitor: '監控；監視器',
  motive: '動機；目的',
  neglect: '忽視；疏忽',
  negotiate: '談判；協商',
  nonetheless: '然而；儘管如此',
  notion: '概念；想法',
  nurture: '培育；養育',
  objective: '目標；客觀的',
  obscure: '模糊的；不清楚的；使模糊',
  obtain: '獲得；取得',
  occupy: '佔據；佔用；從事',
  occur: '發生；出現',
  ongoing: '持續的；進行中的',
  operate: '操作；運作；動手術',
  option: '選項；選擇權',
  orient: '定向；使適應',
  outline: '概述；輪廓；大綱',
  output: '產出；輸出',
  overlook: '忽略；俯瞰',
  overwhelm: '壓倒；使不知所措',
  participate: '參與；參加',
  passive: '被動的；消極的',
  persist: '堅持；持續',
  perspective: '觀點；視角；透視',
  phenomenon: '現象；非凡的事物',
  pioneer: '先驅；開拓者',
  policy: '政策；方針；保單',
  portion: '部分；一份',
  postpone: '延期；推遲',
  potential: '潛力；潛在的',
  precise: '精確的；準確的',
  predict: '預測；預言',
  preliminary: '初步的；預備的',
  premise: '前提；假設',
  preserve: '保存；保護；維持',
  presume: '假定；推測',
  previous: '先前的；以前的',
  primarily: '主要地；首先',
  priority: '優先事項；優先權',
  proceed: '繼續；進行',
  profound: '深刻的；深遠的',
  prohibit: '禁止；阻止',
  promote: '促進；推廣；晉升',
  proportion: '比例；部分',
  prosper: '繁榮；興旺',
  protocol: '協議；禮儀；規範',
  pursue: '追求；追趕；從事',
  qualify: '使合格；限定',
  random: '隨機的；任意的',
  rational: '理性的；合理的',
  reconcile: '調和；和解',
  recover: '恢復；康復；找回',
  reflect: '反映；反射；思考',
  reform: '改革；革新',
  reinforce: '加強；增援',
  reject: '拒絕；駁回',
  reluctant: '不情願的；勉強的',
  rely: '依靠；信賴',
  remedy: '補救；治療；補救措施',
  render: '使成為；提供；渲染',
  represent: '代表；表示；描繪',
  reproduce: '複製；繁殖；再現',
  resemble: '類似；像',
  reside: '居住；存在於',
  resource: '資源；來源',
  respond: '回應；回答',
  restrain: '抑制；限制；克制',
  retain: '保留；保持；記住',
  retrieve: '取回；檢索；恢復',
  reveal: '揭示；透露',
  revenue: '收入；稅收',
  revise: '修改；修訂；複習',
  revolve: '旋轉；圍繞',
  robust: '強健的；堅固的',
  sacrifice: '犧牲；獻祭',
  scenario: '情境；劇本；方案',
  schedule: '時間表；安排；計畫',
  secure: '安全的；確保；獲得',
  segment: '部分；段；區塊',
  severe: '嚴重的；嚴厲的',
  shelter: '庇護所；遮蔽；保護',
  significant: '重要的；顯著的',
  simulate: '模擬；仿真',
  solely: '僅僅；唯獨',
  solidarity: '團結；一致',
  sophisticated: '精密的；世故的；複雜的',
  source: '來源；根源；出處',
  speculate: '推測；投機',
  stable: '穩定的；馬廄',
  stimulate: '刺激；激發',
  straightforward: '直接的；坦率的；簡單的',
  stress: '壓力；強調；重音',
  structure: '結構；構造；組織',
  subsequent: '隨後的；後來的',
  substance: '物質；實質；要旨',
  substitute: '替代；替代品',
  subtle: '微妙的；細微的',
  sufficient: '足夠的；充分的',
  summary: '摘要；總結',
  suppress: '壓制；抑制；隱瞞',
  surplus: '剩餘；盈餘',
  suspend: '暫停；懸掛；中止',
  sustain: '維持；支撐；遭受',
  sympathy: '同情；同感',
  tangible: '有形的；切實的',
  tendency: '趨勢；傾向',
  tension: '緊張；張力',
  theme: '主題；題材',
  thereby: '從而；因此',
  thrive: '茁壯成長；蓬勃發展',
  tolerate: '容忍；忍受',
  transfer: '轉移；調動；轉帳',
  transform: '轉變；改造',
  transmit: '傳輸；傳送；傳播',
  transparent: '透明的；坦誠的',
  trigger: '觸發；引發；扳機',
  ultimate: '最終的；根本的',
  undermine: '破壞；損害；削弱',
  undertake: '承擔；從事',
  unique: '獨特的；唯一的',
  utilize: '利用；使用',
  variable: '變數；可變的',
  venture: '冒險事業；風險投資',
  version: '版本；說法',
  virtual: '虛擬的；實質上的',
  vision: '願景；視力；遠見',
  vital: '至關重要的；生命的',
  voluntary: '自願的；志願的',
  vulnerable: '脆弱的；易受傷害的',
};

function needsZh(meaning) {
  if (!meaning) return true;
  return /^[a-zA-Z("]/.test(meaning.trim());
}

const data = JSON.parse(readFileSync(dataPath, 'utf-8'));
let fixedMap = 0, fixedPrefix = 0;

for (const w of data.vocabulary) {
  if (!needsZh(w.meaning)) continue;

  // Case 1: has Chinese after "word ：" prefix
  if (w.meaning && /[：:]/.test(w.meaning) && /[\u4e00-\u9fff]/.test(w.meaning)) {
    w.meaning = w.meaning.replace(/^[^：:]+[：:]\s*/, '');
    fixedPrefix++;
    continue;
  }

  // Case 2: use hardcoded map
  const zh = ZH_MAP[w.word.toLowerCase()];
  if (zh) {
    w.meaning = zh;
    fixedMap++;
  }
}

writeFileSync(dataPath, JSON.stringify(data, null, 2));
console.log(`完成：對照表修復 ${fixedMap} 個 + 去前綴修復 ${fixedPrefix} 個`);

// Check remaining
const still = data.vocabulary.filter(w => needsZh(w.meaning));
console.log(`仍缺中文意思: ${still.length}`);
if (still.length > 0) {
  still.slice(0, 10).forEach(w => console.log('  ' + w.word));
}
